import{a as v,S as w,i as l}from"./assets/vendor-DnCMJMY2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const q="https://pixabay.com/api/",M="55689404-30812b5f2fcb74649db21ff43";async function u(o,t){return(await v.get(q,{params:{key:M,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),m=document.querySelector(".load-more"),$=new w(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:s,largeImageURL:i,tags:e,likes:r,views:a,comments:L,downloads:S})=>`<li class="gallery-item">
            <a class="gallery-link" href="${i}">
            <img class="gallery-image" src="${s}" alt="${e}" />
            </a>

        <div class="info">
            <p class="info-item"><b>Likes</b> ${r}</p>
            <p class="info-item"><b>Views</b> ${a}</p>
            <p class="info-item"><b>Comments</b> ${L}</p>
            <p class="info-item"><b>Downloads</b> ${S}</p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",t),$.refresh()}function x(){f.innerHTML=""}function h(){p.classList.remove("is-hidden")}function g(){p.classList.add("is-hidden")}function B(){m.classList.remove("is-hidden")}function b(){m.classList.add("is-hidden")}const P=document.querySelector(".form"),O=document.querySelector(".load-more");let n=1,c="",d=0;const R=15;async function j(o){if(o.preventDefault(),c=o.currentTarget.elements["search-text"].value.trim(),n=1,!!c){b(),x(),h();try{const t=await u(c,n);if(t.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}d=Math.ceil(t.totalHits/R),y(t.hits),n=2,d>1&&B()}catch{l.error({message:"Sorry, some error just happen",position:"topRight"})}finally{g()}}}async function D(o){h();try{const t=await u(c,n);y(t.hits);const s=document.querySelector(".gallery-item"),i=s.getBoundingClientRect().height;if(!s)return;if(window.scrollBy({top:i*2,behavior:"smooth"}),n>=d){b(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}n+=1}catch{l.error({message:"Sorry, some error just happen",position:"topRight"})}finally{g()}}P.addEventListener("submit",j);O.addEventListener("click",D);
//# sourceMappingURL=index.js.map
