import{a as w,S as q,i as l}from"./assets/vendor-DnCMJMY2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const M="https://pixabay.com/api/",$="55689404-30812b5f2fcb74649db21ff43";async function f(o,t){return(await w.get(M,{params:{key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const p=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more"),x=new q(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function h(o){const t=o.map(({webformatURL:s,largeImageURL:i,tags:e,likes:r,views:a,comments:S,downloads:v})=>`<li class="gallery-item">
            <a class="gallery-link" href="${i}">
            <img class="gallery-image" src="${s}" alt="${e}" />
            </a>

        <div class="info">
            <p class="info-item"><b>Likes</b> ${r}</p>
            <p class="info-item"><b>Views</b> ${a}</p>
            <p class="info-item"><b>Comments</b> ${S}</p>
            <p class="info-item"><b>Downloads</b> ${v}</p>
        </div>
      </li>`).join("");p.insertAdjacentHTML("beforeend",t),x.refresh()}function B(){p.innerHTML=""}function g(){m.classList.remove("is-hidden")}function b(){m.classList.add("is-hidden")}function d(){y.classList.remove("is-hidden")}function L(){y.classList.add("is-hidden")}const P=document.querySelector(".form"),O=document.querySelector(".load-more");let n=1,c="",u=0;const R=15;async function j(o){if(o.preventDefault(),c=o.currentTarget.elements["search-text"].value.trim(),n=1,!!c){L(),B(),g();try{const t=await f(c,n);if(t.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}u=Math.ceil(t.totalHits/R),h(t.hits),n=2,u>1&&d()}catch{l.error({message:"Sorry, some error just happen",position:"topRight"})}finally{b()}}}async function D(o){L(),g();try{const t=await f(c,n);h(t.hits);const s=document.querySelector(".gallery-item");if(!s)return;const i=s.getBoundingClientRect().height;if(window.scrollBy({top:i*2,behavior:"smooth"}),n>=u){l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}n+=1,d()}catch{l.error({message:"Sorry, some error just happen",position:"topRight"}),d()}finally{b()}}P.addEventListener("submit",j);O.addEventListener("click",D);
//# sourceMappingURL=index.js.map
